---
services:
  front:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "80:4200"  # Angular servirá en el puerto 4200
    depends_on:
      - back

  back:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "2000:2000"  # Express servirá en el puerto 3000
    environment:
      MONGO_URL: mongodb+srv://agugabriel94:jsDw7hP9Jwdouwjj@saludsabor.cg29a0u.mongodb.net/SaludySabor?retryWrites=true&w=majority&appName=SaludSabor
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
