version: '3'
services:
  backend:
    build:
      context: ./BACKEND
    ports:
      - "2000:2000"
    volumes:
      - ./BACKEND:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./FRONTEND
    ports:
      - "80:80"  # Cambiar el puerto a 80 porque es el que usa nginx
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
