---
services:
  front:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "80:4200"  # Angular servirá en el puerto 4200
    depends_on:
      - back

  back:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Express servirá en el puerto 3000
    environment:
      MONGO_URL: mongodb://mongo:27017/testdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
